export type WidgetCopy = {
  greeting: string;
  assistantSubtitle: string;
  welcomeEyebrow: string;
  welcomeTitle: string;
  welcomeBody: string;
  welcomeNext: string;
  privacyTitle: string;
  privacyBody: string;
  privacyAcknowledgment: string;
  accept: string;
  decline: string;
  inputPlaceholder: string;
  send: string;
  newChat: string;
  newChatConfirmation: string;
  confirmNewChat: string;
  cancelNewChat: string;
  support: string;
  supportQueued: string;
  supportFailed: string;
  supportCreating: string;
  supportRequested: string;
  supportFormTitle: string;
  supportFormBody: string;
  supportFirstName: string;
  supportEmail: string;
  supportQuestion: string;
  supportSubmit: string;
  supportCancel: string;
  supportPrivacy: string;
  supportInvalidEmail: string;
  supportNoRoute: string;
  conversationCleared: string;
  footer: string;
  online: string;
  offline: string;
  reconnecting: string;
  consentRequired: string;
  unavailable: string;
  waiting: string;
  copy: string;
  copied: string;
  helpful: string;
  notHelpful: string;
  feedbackLabel: string;
  feedbackPrivacyNote: string;
  feedbackPlaceholder: string;
  feedbackSend: string;
  feedbackSkip: string;
  feedbackSent: string;
  feedbackError: string;
  privacyEyebrow: string;
  reviewDocuments: string;
  privacyLoading: string;
  privacySaving: string;
  privacySaved: string;
  declineTitle: string;
  declineBody: string;
  reviewPrivacy: string;
  market: string;
  language: string;
  selectMarket: string;
  selectLanguage: string;
  openAssistant: string;
  closeAssistant: string;
  openMenu: string;
  composerHint: string;
  thinking: string;
  searching: string;
  generating: string;
  retrying: string;
  slowResponse: string;
  you: string;
  system: string;
  sourcesUsed: string;
  references: string;
  primarySource: string;
  supportingSource: string;
  source: string;
  section: string;
  openSource: string;
  saveAsPdf: string;
  closeLegal: string;
  retry: string;
};

const copy: Record<string, Partial<WidgetCopy>> = {
  en: {
    greeting: "Hi, I'm AskVera. I can help you find approved answers from Forever Living company policies and the global office directory. What would you like to know?",
    assistantSubtitle: "Enterprise Knowledge Assistant",
    welcomeEyebrow: "Welcome", welcomeTitle: "Hi, I'm AskVera.",
    welcomeBody: "I can help you find approved answers from Forever Living company policies and the global office directory.",
    welcomeNext: "Choose your market and language to begin.", privacyTitle: "Privacy and Terms",
    privacyBody: "Review and accept the required legal documents to use AskVera.",
    privacyAcknowledgment: "I have read and agree to the required privacy and terms documents.",
    accept: "I agree", decline: "Not now", inputPlaceholder: "Ask a question", send: "Send message",
    newChat: "Start new chat", newChatConfirmation: "Starting a new chat will end and clear this conversation.", confirmNewChat: "Start new chat", cancelNewChat: "Cancel", support: "Request support", supportQueued: "Your support request was submitted. Reference: {id}",
    supportFailed: "The support request could not be created. Please try again.", supportCreating: "Creating...", supportRequested: "Requested", conversationCleared: "A new chat is ready.",
    supportFormTitle: "Request support", supportFormBody: "Send your question to the support team for your market.", supportFirstName: "First name", supportEmail: "Email", supportQuestion: "Question or issue", supportSubmit: "Send request", supportCancel: "Cancel", supportPrivacy: "Your details are used only to respond to this support request.", supportInvalidEmail: "Enter a valid email address.", supportNoRoute: "Support requests are not yet available for this market.",
    footer: "Answers are generated by AI from approved company documents and may contain errors. Verify important information against the cited source documents.", online: "Online", offline: "Offline",
    reconnecting: "Reconnecting", consentRequired: "Accept the privacy agreement to begin.", unavailable: "AskVera is temporarily unavailable. Please try again in a moment.", waiting: "Waiting for the current response to finish.", copy: "Copy", copied: "Copied", helpful: "Helpful", notHelpful: "Not helpful",
    privacyEyebrow: "One quick privacy step", reviewDocuments: "Review required documents",
    privacyLoading: "Loading legal documents before consent can be recorded.", privacySaving: "Saving...",
    privacySaved: "Privacy saved. Chat is ready.", declineTitle: "No problem. AskVera will be here when you are ready.",
    declineBody: "To start chatting, return and accept the privacy and terms when you are ready.", reviewPrivacy: "Review privacy terms",
    market: "Market", language: "Language", selectMarket: "Select a market", selectLanguage: "Select a language",
    openAssistant: "Open AskVera", closeAssistant: "Close AskVera", openMenu: "Open AskVera menu", composerHint: "Enter to send. Shift + Enter for a new line.",
    thinking: "Thinking...", searching: "Searching approved documentation...", generating: "Preparing your answer...", retrying: "Connection interrupted. Retrying...", slowResponse: "Still working...",
    you: "You", system: "System", sourcesUsed: "Sources used for this answer", references: "References", primarySource: "Primary source", supportingSource: "Supporting source", source: "Source", section: "Section", openSource: "View exact source",
    saveAsPdf: "Save as PDF", closeLegal: "Close legal document", retry: "Retry"
  },
  fr: {
    greeting: "Bonjour, je suis AskVera. Je peux vous aider à trouver des réponses approuvées dans les politiques de Forever Living et l'annuaire mondial des bureaux. Que souhaitez-vous savoir?",
    assistantSubtitle: "Assistant de connaissances d'entreprise",
    welcomeEyebrow: "Bienvenue", welcomeTitle: "Bonjour, je suis AskVera.",
    welcomeBody: "Je peux vous aider à trouver des réponses approuvées dans les politiques de Forever Living et l'annuaire mondial des bureaux.",
    welcomeNext: "Choisissez votre marché et votre langue pour commencer.", privacyTitle: "Confidentialité et conditions",
    privacyBody: "Consultez et acceptez les documents juridiques requis pour utiliser AskVera.",
    privacyAcknowledgment: "J'ai lu et j'accepte les documents requis sur la confidentialité et les conditions.",
    accept: "J'accepte", decline: "Pas maintenant", inputPlaceholder: "Posez une question", send: "Envoyer",
    newChat: "Démarrer une nouvelle conversation", newChatConfirmation: "Démarrer une nouvelle conversation mettra fin à celle-ci et effacera son contenu.", confirmNewChat: "Démarrer", cancelNewChat: "Annuler", support: "Demander de l'aide", supportQueued: "Votre demande d'aide a été envoyée. Référence : {id}",
    supportFailed: "La demande d'aide n'a pas pu être créée. Veuillez réessayer.", supportCreating: "Création...", supportRequested: "Demandé", conversationCleared: "Une nouvelle conversation est prête.",
    footer: "Les réponses sont générées par l’IA à partir de documents approuvés et peuvent contenir des erreurs. Vérifiez les informations importantes dans les documents sources cités.", online: "En ligne", offline: "Hors ligne",
    reconnecting: "Reconnexion", consentRequired: "Acceptez l'accord de confidentialité pour commencer.", unavailable: "AskVera est temporairement indisponible. Veuillez réessayer dans un instant.", waiting: "Attendez la fin de la réponse en cours.", copy: "Copier", copied: "Copié", helpful: "Utile", notHelpful: "Pas utile",
    privacyEyebrow: "Une étape rapide de confidentialité", reviewDocuments: "Consulter les documents requis", privacyLoading: "Chargement des documents juridiques...", privacySaving: "Enregistrement...", privacySaved: "Confidentialité enregistrée. Le chat est prêt.", declineTitle: "Aucun problème. AskVera sera là quand vous serez prêt.", declineBody: "Pour discuter, revenez accepter les conditions de confidentialité.", reviewPrivacy: "Consulter les conditions", market: "Marché", language: "Langue", selectMarket: "Sélectionnez un marché", selectLanguage: "Sélectionnez une langue", openAssistant: "Ouvrir AskVera", closeAssistant: "Fermer AskVera", openMenu: "Ouvrir le menu AskVera", composerHint: "Entrée pour envoyer. Maj + Entrée pour une nouvelle ligne.", thinking: "Réflexion...", searching: "Recherche dans les documents approuvés...", generating: "Préparation de votre réponse...", retrying: "Connexion interrompue. Nouvelle tentative...", slowResponse: "Toujours en cours...", you: "Vous", system: "Système", sourcesUsed: "Sources utilisées pour cette réponse", references: "Références", primarySource: "Source principale", supportingSource: "Source complémentaire", source: "Source", section: "Section", openSource: "Voir la source exacte", saveAsPdf: "Enregistrer en PDF", closeLegal: "Fermer le document juridique"
  },
  es: {
    greeting: "Hola, soy AskVera. Puedo ayudarte a encontrar respuestas aprobadas en las políticas de Forever Living y el directorio mundial de oficinas. ¿Qué deseas saber?",
    assistantSubtitle: "Asistente de conocimiento empresarial",
    welcomeEyebrow: "Bienvenido", welcomeTitle: "Hola, soy AskVera.",
    welcomeBody: "Puedo ayudarte a encontrar respuestas aprobadas en las políticas de Forever Living y el directorio mundial de oficinas.",
    welcomeNext: "Elige tu mercado e idioma para comenzar.", privacyTitle: "Privacidad y condiciones",
    privacyBody: "Revisa y acepta los documentos legales requeridos para usar AskVera.",
    privacyAcknowledgment: "He leído y acepto los documentos requeridos de privacidad y condiciones.",
    accept: "Acepto", decline: "Ahora no", inputPlaceholder: "Haz una pregunta", send: "Enviar",
    newChat: "Iniciar un nuevo chat", newChatConfirmation: "Al iniciar un nuevo chat, esta conversación finalizará y se borrará.", confirmNewChat: "Iniciar chat", cancelNewChat: "Cancelar", support: "Solicitar ayuda", supportQueued: "Tu solicitud de ayuda fue enviada. Referencia: {id}",
    supportFailed: "No se pudo crear la solicitud de ayuda. Inténtalo de nuevo.", supportCreating: "Creando...", supportRequested: "Solicitado", conversationCleared: "Hay un nuevo chat listo.",
    footer: "Las respuestas son generadas por IA a partir de documentos aprobados y pueden contener errores. Verifica la información importante en los documentos fuente citados.", online: "En línea", offline: "Sin conexión",
    reconnecting: "Reconectando", consentRequired: "Acepta el acuerdo de privacidad para comenzar.", unavailable: "AskVera no está disponible temporalmente. Inténtalo de nuevo en un momento.", waiting: "Espera a que termine la respuesta actual.", copy: "Copiar", copied: "Copiado", helpful: "Útil", notHelpful: "No útil",
    privacyEyebrow: "Un paso rápido de privacidad", reviewDocuments: "Revisar los documentos requeridos", privacyLoading: "Cargando los documentos legales...", privacySaving: "Guardando...", privacySaved: "Privacidad guardada. El chat está listo.", declineTitle: "No hay problema. AskVera estará aquí cuando estés listo.", declineBody: "Para chatear, vuelve y acepta la privacidad y las condiciones.", reviewPrivacy: "Revisar privacidad y condiciones", market: "Mercado", language: "Idioma", selectMarket: "Selecciona un mercado", selectLanguage: "Selecciona un idioma", openAssistant: "Abrir AskVera", closeAssistant: "Cerrar AskVera", openMenu: "Abrir el menú de AskVera", composerHint: "Enter para enviar. Mayús + Enter para una nueva línea.", thinking: "Pensando...", searching: "Buscando en la documentación aprobada...", generating: "Preparando tu respuesta...", retrying: "Conexión interrumpida. Reintentando...", slowResponse: "Sigo trabajando...", you: "Tú", system: "Sistema", sourcesUsed: "Fuentes utilizadas para esta respuesta", references: "Referencias", primarySource: "Fuente principal", supportingSource: "Fuente complementaria", source: "Fuente", section: "Sección", openSource: "Ver fuente exacta", saveAsPdf: "Guardar como PDF", closeLegal: "Cerrar documento legal"
  },
  ru: {
    greeting: "Здравствуйте, я AskVera. Я помогу найти утвержденную информацию в политиках компании Forever Living и глобальном справочнике офисов. Что вы хотели бы узнать?",
    assistantSubtitle: "Корпоративный информационный помощник",
    welcomeEyebrow: "Добро пожаловать",
    welcomeTitle: "Здравствуйте, я AskVera.",
    welcomeBody: "Я помогу найти утвержденную информацию в политиках компании Forever Living и глобальном справочнике офисов.",
    welcomeNext: "Выберите рынок и язык, чтобы начать.",
    privacyTitle: "Конфиденциальность и условия",
    privacyBody: "Ознакомьтесь с обязательными юридическими документами и примите их, чтобы пользоваться AskVera.",
    privacyAcknowledgment: "Я прочитал(а) и принимаю обязательные документы о конфиденциальности и условиях.",
    accept: "Я согласен(на)",
    decline: "Не сейчас",
    inputPlaceholder: "Задайте вопрос",
    send: "Отправить",
    newChat: "Начать новый чат",
    newChatConfirmation: "При запуске нового чата текущая беседа будет завершена и очищена.",
    confirmNewChat: "Начать новый чат",
    cancelNewChat: "Отмена",
    support: "Запросить поддержку",
    supportQueued: "Ваш запрос в поддержку отправлен. Номер: {id}",
    supportFailed: "Не удалось создать запрос в поддержку. Повторите попытку.",
    supportCreating: "Создание...",
    supportRequested: "Отправлено",
    supportFormTitle: "Запросить поддержку",
    supportFormBody: "Отправьте свой вопрос в службу поддержки выбранного рынка.",
    supportFirstName: "Имя",
    supportEmail: "Электронная почта",
    supportQuestion: "Вопрос или проблема",
    supportSubmit: "Отправить запрос",
    supportCancel: "Отмена",
    supportPrivacy: "Ваши данные используются только для ответа на этот запрос в поддержку.",
    supportInvalidEmail: "Введите действительный адрес электронной почты.",
    supportNoRoute: "Запросы в поддержку пока недоступны для этого рынка.",
    conversationCleared: "Новый чат готов.",
    footer: "Ответы создаются ИИ на основе утвержденных документов компании и могут содержать ошибки. Проверяйте важную информацию по указанным источникам.",
    online: "В сети",
    offline: "Не в сети",
    reconnecting: "Повторное подключение",
    consentRequired: "Примите соглашение о конфиденциальности, чтобы начать.",
    unavailable: "AskVera временно недоступна. Повторите попытку через минуту.",
    waiting: "Дождитесь завершения текущего ответа.",
    copy: "Копировать",
    copied: "Скопировано",
    helpful: "Полезно",
    notHelpful: "Не помогло",
    privacyEyebrow: "Небольшой шаг по конфиденциальности",
    reviewDocuments: "Просмотреть обязательные документы",
    privacyLoading: "Загрузка юридических документов...",
    privacySaving: "Сохранение...",
    privacySaved: "Согласие сохранено. Чат готов.",
    declineTitle: "Ничего страшного. AskVera будет здесь, когда вы будете готовы.",
    declineBody: "Чтобы начать чат, вернитесь и примите условия конфиденциальности.",
    reviewPrivacy: "Просмотреть условия конфиденциальности",
    market: "Рынок",
    language: "Язык",
    selectMarket: "Выберите рынок",
    selectLanguage: "Выберите язык",
    openAssistant: "Открыть AskVera",
    closeAssistant: "Закрыть AskVera",
    openMenu: "Открыть меню AskVera",
    composerHint: "Enter - отправить. Shift + Enter - новая строка.",
    thinking: "Думаю...",
    searching: "Поиск в утвержденных документах...",
    generating: "Подготовка ответа...",
    retrying: "Соединение прервано. Повторная попытка...",
    slowResponse: "Работа еще продолжается...",
    you: "Вы",
    system: "Система",
    sourcesUsed: "Источники этого ответа",
    references: "Ссылки",
    primarySource: "Основной источник",
    supportingSource: "Дополнительный источник",
    source: "Источник",
    section: "Раздел",
    openSource: "Открыть точный источник",
    saveAsPdf: "Сохранить как PDF",
    closeLegal: "Закрыть юридический документ",
    retry: "Повторить"
  },
  de: {
    greeting: "Hallo, ich bin AskVera. Ich helfe Ihnen, freigegebene Antworten in den Forever Living Unternehmensrichtlinien und im weltweiten Büroverzeichnis zu finden. Was möchten Sie wissen?",
    assistantSubtitle: "Unternehmens-Wissensassistent",
    welcomeEyebrow: "Willkommen", welcomeTitle: "Hallo, ich bin AskVera.",
    welcomeBody: "Ich helfe Ihnen, freigegebene Antworten in den Forever Living Unternehmensrichtlinien und im weltweiten Büroverzeichnis zu finden.",
    welcomeNext: "Wählen Sie Ihren Markt und Ihre Sprache aus.", privacyTitle: "Datenschutz und Bedingungen",
    privacyBody: "Prüfen und akzeptieren Sie die erforderlichen rechtlichen Dokumente, um AskVera zu verwenden.",
    privacyAcknowledgment: "Ich habe die erforderlichen Datenschutz- und Bedingungsdokumente gelesen und stimme ihnen zu.",
    accept: "Ich stimme zu", decline: "Nicht jetzt", inputPlaceholder: "Frage stellen", send: "Senden",
    newChat: "Neuen Chat starten", newChatConfirmation: "Ein neuer Chat beendet und löscht diese Unterhaltung.", confirmNewChat: "Chat starten", cancelNewChat: "Abbrechen", support: "Support anfordern", supportQueued: "Ihre Supportanfrage wurde übermittelt. Referenz: {id}",
    supportFailed: "Die Supportanfrage konnte nicht erstellt werden. Bitte versuchen Sie es erneut.", supportCreating: "Wird erstellt...", supportRequested: "Angefordert", conversationCleared: "Ein neuer Chat ist bereit.",
    supportFormTitle: "Support anfordern", supportFormBody: "Senden Sie Ihre Frage an das Support-Team Ihres Marktes.", supportFirstName: "Vorname", supportEmail: "E-Mail", supportQuestion: "Frage oder Anliegen", supportSubmit: "Anfrage senden", supportCancel: "Abbrechen", supportPrivacy: "Ihre Angaben werden nur zur Bearbeitung dieser Supportanfrage verwendet.", supportInvalidEmail: "Geben Sie eine gültige E-Mail-Adresse ein.", supportNoRoute: "Supportanfragen sind für diesen Markt noch nicht verfügbar.",
    footer: "Antworten werden von KI aus freigegebenen Unternehmensdokumenten erstellt und können Fehler enthalten. Prüfen Sie wichtige Informationen anhand der zitierten Quelldokumente.", online: "Online", offline: "Offline",
    reconnecting: "Verbindung wird hergestellt", consentRequired: "Akzeptieren Sie die Datenschutzvereinbarung, um zu beginnen.", unavailable: "AskVera ist vorübergehend nicht verfügbar. Versuchen Sie es gleich noch einmal.", waiting: "Warten Sie, bis die aktuelle Antwort abgeschlossen ist.", copy: "Kopieren", copied: "Kopiert", helpful: "Hilfreich", notHelpful: "Nicht hilfreich",
    privacyEyebrow: "Ein kurzer Datenschutzschritt", reviewDocuments: "Erforderliche Dokumente prüfen", privacyLoading: "Rechtliche Dokumente werden geladen...", privacySaving: "Wird gespeichert...", privacySaved: "Datenschutz gespeichert. Der Chat ist bereit.", declineTitle: "Kein Problem. AskVera ist da, wenn Sie bereit sind.", declineBody: "Akzeptieren Sie die Datenschutzbestimmungen, um den Chat zu starten.", reviewPrivacy: "Datenschutz prüfen", market: "Markt", language: "Sprache", selectMarket: "Markt auswählen", selectLanguage: "Sprache auswählen", openAssistant: "AskVera öffnen", closeAssistant: "AskVera schließen", openMenu: "AskVera-Menü öffnen", composerHint: "Eingabetaste zum Senden. Umschalt + Eingabetaste für eine neue Zeile.", thinking: "Denke nach...", searching: "Freigegebene Dokumente werden durchsucht...", generating: "Antwort wird vorbereitet...", retrying: "Verbindung unterbrochen. Neuer Versuch...", slowResponse: "Noch in Bearbeitung...", you: "Sie", system: "System", sourcesUsed: "Quellen für diese Antwort", references: "Referenzen", primarySource: "Primärquelle", supportingSource: "Ergänzende Quelle", source: "Quelle", section: "Abschnitt", openSource: "Genaue Quelle anzeigen", saveAsPdf: "Als PDF speichern", closeLegal: "Rechtsdokument schließen"
  },
  nl: {
    greeting: "Hallo, ik ben AskVera. Ik help u goedgekeurde antwoorden te vinden in het bedrijfsbeleid van Forever Living en de wereldwijde kantorengids. Wat wilt u weten?",
    assistantSubtitle: "Kennisassistent voor bedrijven",
    welcomeEyebrow: "Welkom", welcomeTitle: "Hallo, ik ben AskVera.",
    welcomeBody: "Ik help u goedgekeurde antwoorden te vinden in het bedrijfsbeleid van Forever Living en de wereldwijde kantorengids.",
    welcomeNext: "Kies uw markt en taal om te beginnen.", privacyTitle: "Privacy en voorwaarden",
    privacyBody: "Bekijk en accepteer de vereiste juridische documenten om AskVera te gebruiken.",
    privacyAcknowledgment: "Ik heb de vereiste privacy- en voorwaardendocumenten gelezen en ga ermee akkoord.",
    accept: "Ik ga akkoord", decline: "Niet nu", inputPlaceholder: "Stel een vraag", send: "Versturen",
    newChat: "Nieuwe chat starten", newChatConfirmation: "Een nieuwe chat beëindigt en wist dit gesprek.", confirmNewChat: "Chat starten", cancelNewChat: "Annuleren", support: "Hulp aanvragen", supportQueued: "Uw hulpverzoek is verzonden. Referentie: {id}",
    supportFailed: "Het hulpverzoek kon niet worden aangemaakt. Probeer het opnieuw.", supportCreating: "Aanmaken...", supportRequested: "Aangevraagd", conversationCleared: "Een nieuwe chat staat klaar.",
    supportFormTitle: "Hulp aanvragen", supportFormBody: "Stuur uw vraag naar het supportteam voor uw markt.", supportFirstName: "Voornaam", supportEmail: "E-mail", supportQuestion: "Vraag of probleem", supportSubmit: "Verzoek versturen", supportCancel: "Annuleren", supportPrivacy: "Uw gegevens worden alleen gebruikt om op dit supportverzoek te reageren.", supportInvalidEmail: "Voer een geldig e-mailadres in.", supportNoRoute: "Supportverzoeken zijn nog niet beschikbaar voor deze markt.",
    footer: "Antwoorden worden door AI gegenereerd op basis van goedgekeurde bedrijfsdocumenten en kunnen fouten bevatten. Controleer belangrijke informatie in de vermelde brondocumenten.", online: "Online", offline: "Offline",
    reconnecting: "Opnieuw verbinden", consentRequired: "Accepteer de privacyovereenkomst om te beginnen.", unavailable: "AskVera is tijdelijk niet beschikbaar. Probeer het zo opnieuw.", waiting: "Wacht tot het huidige antwoord klaar is.", copy: "Kopiëren", copied: "Gekopieerd", helpful: "Nuttig", notHelpful: "Niet nuttig",
    privacyEyebrow: "Een korte privacystap", reviewDocuments: "Vereiste documenten bekijken", privacyLoading: "Juridische documenten worden geladen...", privacySaving: "Opslaan...", privacySaved: "Privacy opgeslagen. De chat is klaar.", declineTitle: "Geen probleem. AskVera is er wanneer u klaar bent.", declineBody: "Accepteer de privacyvoorwaarden om te beginnen.", reviewPrivacy: "Privacyvoorwaarden bekijken", market: "Markt", language: "Taal", selectMarket: "Selecteer een markt", selectLanguage: "Selecteer een taal", openAssistant: "AskVera openen", closeAssistant: "AskVera sluiten", openMenu: "AskVera-menu openen", composerHint: "Enter om te verzenden. Shift + Enter voor een nieuwe regel.", thinking: "Even nadenken...", searching: "Goedgekeurde documentatie doorzoeken...", generating: "Uw antwoord voorbereiden...", retrying: "Verbinding verbroken. Opnieuw proberen...", slowResponse: "Nog bezig...", you: "U", system: "Systeem", sourcesUsed: "Bronnen voor dit antwoord", references: "Referenties", primarySource: "Primaire bron", supportingSource: "Aanvullende bron", source: "Bron", section: "Sectie", openSource: "Exacte bron bekijken", saveAsPdf: "Opslaan als PDF", closeLegal: "Juridisch document sluiten"
  },
  it: {
    greeting: "Ciao, sono AskVera. Posso aiutarti a trovare risposte approvate nelle politiche aziendali Forever Living e nell'elenco globale degli uffici. Cosa vorresti sapere?",
    assistantSubtitle: "Assistente alla conoscenza aziendale",
    welcomeEyebrow: "Benvenuto", welcomeTitle: "Ciao, sono AskVera.", welcomeBody: "Posso aiutarti a trovare risposte approvate nelle politiche aziendali Forever Living e nell'elenco globale degli uffici.", welcomeNext: "Scegli il mercato e la lingua per iniziare.",
    privacyTitle: "Privacy e condizioni", privacyBody: "Consulta e accetta i documenti legali richiesti per usare AskVera.", privacyAcknowledgment: "Ho letto e accetto i documenti richiesti sulla privacy e le condizioni.", accept: "Accetto", decline: "Non ora", inputPlaceholder: "Fai una domanda", send: "Invia",
    newChat: "Avvia una nuova chat", newChatConfirmation: "Avviare una nuova chat terminerà e cancellerà questa conversazione.", confirmNewChat: "Avvia chat", cancelNewChat: "Annulla", support: "Richiedi assistenza", supportQueued: "La richiesta di assistenza è stata inviata. Riferimento: {id}", supportFailed: "Impossibile creare la richiesta. Riprova.", supportCreating: "Creazione...", supportRequested: "Richiesta", conversationCleared: "Una nuova chat è pronta.",
    supportFormTitle: "Richiedi assistenza", supportFormBody: "Invia la tua domanda al team di assistenza del tuo mercato.", supportFirstName: "Nome", supportEmail: "Email", supportQuestion: "Domanda o problema", supportSubmit: "Invia richiesta", supportCancel: "Annulla", supportPrivacy: "I tuoi dati saranno utilizzati solo per rispondere a questa richiesta.", supportInvalidEmail: "Inserisci un indirizzo email valido.", supportNoRoute: "Le richieste di assistenza non sono ancora disponibili per questo mercato.",
    footer: "Le risposte sono generate dall'IA a partire da documenti aziendali approvati e possono contenere errori. Verifica le informazioni importanti nei documenti citati.", online: "Online", offline: "Offline", reconnecting: "Riconnessione", consentRequired: "Accetta l'informativa sulla privacy per iniziare.", unavailable: "AskVera non è temporaneamente disponibile. Riprova tra poco.", waiting: "Attendi il completamento della risposta corrente.", copy: "Copia", copied: "Copiato", helpful: "Utile", notHelpful: "Non utile",
    privacyEyebrow: "Un rapido passaggio sulla privacy", reviewDocuments: "Consulta i documenti richiesti", privacyLoading: "Caricamento dei documenti legali...", privacySaving: "Salvataggio...", privacySaved: "Privacy salvata. La chat è pronta.", declineTitle: "Nessun problema. AskVera sarà qui quando sarai pronto.", declineBody: "Per iniziare, torna e accetta privacy e condizioni.", reviewPrivacy: "Consulta privacy e condizioni", market: "Mercato", language: "Lingua", selectMarket: "Seleziona un mercato", selectLanguage: "Seleziona una lingua", openAssistant: "Apri AskVera", closeAssistant: "Chiudi AskVera", openMenu: "Apri il menu AskVera", composerHint: "Invio per spedire. Maiusc + Invio per una nuova riga.", thinking: "Sto pensando...", searching: "Ricerca nella documentazione approvata...", generating: "Preparazione della risposta...", retrying: "Connessione interrotta. Nuovo tentativo...", slowResponse: "Sto ancora lavorando...", you: "Tu", system: "Sistema", sourcesUsed: "Fonti utilizzate per questa risposta", references: "Riferimenti", primarySource: "Fonte principale", supportingSource: "Fonte di supporto", source: "Fonte", section: "Sezione", saveAsPdf: "Salva come PDF", closeLegal: "Chiudi il documento legale"
  },
  da: {
    greeting: "Hej, jeg er AskVera. Jeg kan hjælpe dig med at finde godkendte svar i Forever Livings virksomhedspolitikker og globale kontoroversigt. Hvad vil du gerne vide?",
    assistantSubtitle: "Virksomhedens vidensassistent",
    welcomeEyebrow: "Velkommen", welcomeTitle: "Hej, jeg er AskVera.", welcomeBody: "Jeg kan hjælpe dig med at finde godkendte svar i Forever Livings virksomhedspolitikker og globale kontoroversigt.", welcomeNext: "Vælg marked og sprog for at begynde.",
    privacyTitle: "Privatliv og vilkår", privacyBody: "Gennemgå og accepter de nødvendige juridiske dokumenter for at bruge AskVera.", privacyAcknowledgment: "Jeg har læst og accepterer de nødvendige privatlivs- og vilkårsdokumenter.", accept: "Jeg accepterer", decline: "Ikke nu", inputPlaceholder: "Stil et spørgsmål", send: "Send",
    newChat: "Start ny chat", newChatConfirmation: "En ny chat afslutter og rydder denne samtale.", confirmNewChat: "Start chat", cancelNewChat: "Annuller", support: "Anmod om hjælp", supportQueued: "Din supportanmodning er sendt. Reference: {id}", supportFailed: "Supportanmodningen kunne ikke oprettes. Prøv igen.", supportCreating: "Opretter...", supportRequested: "Anmodet", conversationCleared: "En ny chat er klar.",
    footer: "Svar genereres af AI ud fra godkendte virksomhedsdokumenter og kan indeholde fejl. Kontrollér vigtige oplysninger i de citerede kildedokumenter.", online: "Online", offline: "Offline", reconnecting: "Opretter forbindelse igen", consentRequired: "Accepter privatlivsaftalen for at begynde.", unavailable: "AskVera er midlertidigt utilgængelig. Prøv igen om lidt.", waiting: "Vent på, at det aktuelle svar bliver færdigt.", copy: "Kopiér", copied: "Kopieret", helpful: "Nyttigt", notHelpful: "Ikke nyttigt",
    privacyEyebrow: "Et hurtigt privatlivstrin", reviewDocuments: "Gennemgå nødvendige dokumenter", privacyLoading: "Indlæser juridiske dokumenter...", privacySaving: "Gemmer...", privacySaved: "Privatliv gemt. Chatten er klar.", declineTitle: "Intet problem. AskVera er her, når du er klar.", declineBody: "Vend tilbage og accepter privatliv og vilkår for at begynde.", reviewPrivacy: "Gennemgå privatlivsvilkår", market: "Marked", language: "Sprog", selectMarket: "Vælg et marked", selectLanguage: "Vælg et sprog", openAssistant: "Åbn AskVera", closeAssistant: "Luk AskVera", openMenu: "Åbn AskVera-menu", composerHint: "Enter for at sende. Shift + Enter for en ny linje.", thinking: "Tænker...", searching: "Søger i godkendt dokumentation...", generating: "Forbereder dit svar...", retrying: "Forbindelsen blev afbrudt. Prøver igen...", slowResponse: "Arbejder stadig...", you: "Du", system: "System", sourcesUsed: "Kilder brugt til dette svar", references: "Referencer", primarySource: "Primær kilde", supportingSource: "Supplerende kilde", source: "Kilde", section: "Afsnit", saveAsPdf: "Gem som PDF", closeLegal: "Luk juridisk dokument"
  },
  fi: {
    greeting: "Hei, olen AskVera. Autan löytämään hyväksyttyjä vastauksia Forever Livingin yrityskäytännöistä ja maailmanlaajuisesta toimistohakemistosta. Mitä haluaisit tietää?",
    assistantSubtitle: "Yrityksen tietoavustaja",
    welcomeEyebrow: "Tervetuloa", welcomeTitle: "Hei, olen AskVera.", welcomeBody: "Autan löytämään hyväksyttyjä vastauksia Forever Livingin yrityskäytännöistä ja maailmanlaajuisesta toimistohakemistosta.", welcomeNext: "Valitse markkina ja kieli aloittaaksesi.",
    privacyTitle: "Tietosuoja ja ehdot", privacyBody: "Tutustu vaadittuihin oikeudellisiin asiakirjoihin ja hyväksy ne käyttääksesi AskVeraa.", privacyAcknowledgment: "Olen lukenut ja hyväksyn vaaditut tietosuoja- ja ehtodokumentit.", accept: "Hyväksyn", decline: "Ei nyt", inputPlaceholder: "Kysy kysymys", send: "Lähetä",
    newChat: "Aloita uusi keskustelu", newChatConfirmation: "Uusi keskustelu päättää ja tyhjentää tämän keskustelun.", confirmNewChat: "Aloita", cancelNewChat: "Peruuta", support: "Pyydä tukea", supportQueued: "Tukipyyntösi on lähetetty. Viite: {id}", supportFailed: "Tukipyyntöä ei voitu luoda. Yritä uudelleen.", supportCreating: "Luodaan...", supportRequested: "Pyydetty", conversationCleared: "Uusi keskustelu on valmis.",
    footer: "Vastaukset luodaan tekoälyn avulla hyväksytyistä yritysasiakirjoista, ja niissä voi olla virheitä. Tarkista tärkeät tiedot viitatuista lähdeasiakirjoista.", online: "Online", offline: "Offline", reconnecting: "Yhdistetään uudelleen", consentRequired: "Hyväksy tietosuojasopimus aloittaaksesi.", unavailable: "AskVera ei ole tilapäisesti käytettävissä. Yritä pian uudelleen.", waiting: "Odota nykyisen vastauksen valmistumista.", copy: "Kopioi", copied: "Kopioitu", helpful: "Hyödyllinen", notHelpful: "Ei hyödyllinen",
    privacyEyebrow: "Nopea tietosuojavaihe", reviewDocuments: "Tarkista vaaditut asiakirjat", privacyLoading: "Ladataan oikeudellisia asiakirjoja...", privacySaving: "Tallennetaan...", privacySaved: "Tietosuoja tallennettu. Keskustelu on valmis.", declineTitle: "Ei hätää. AskVera on täällä, kun olet valmis.", declineBody: "Palaa hyväksymään tietosuoja ja ehdot aloittaaksesi.", reviewPrivacy: "Tarkista tietosuojaehdot", market: "Markkina", language: "Kieli", selectMarket: "Valitse markkina", selectLanguage: "Valitse kieli", openAssistant: "Avaa AskVera", closeAssistant: "Sulje AskVera", openMenu: "Avaa AskVera-valikko", composerHint: "Enter lähettää. Shift + Enter lisää uuden rivin.", thinking: "Ajattelen...", searching: "Haetaan hyväksytyistä asiakirjoista...", generating: "Valmistellaan vastausta...", retrying: "Yhteys katkesi. Yritetään uudelleen...", slowResponse: "Työskentelen edelleen...", you: "Sinä", system: "Järjestelmä", sourcesUsed: "Tässä vastauksessa käytetyt lähteet", references: "Viitteet", primarySource: "Ensisijainen lähde", supportingSource: "Tukeva lähde", source: "Lähde", section: "Kohta", saveAsPdf: "Tallenna PDF-muodossa", closeLegal: "Sulje oikeudellinen asiakirja"
  },
  no: {
    greeting: "Hei, jeg er AskVera. Jeg kan hjelpe deg med å finne godkjente svar i Forever Livings selskapsretningslinjer og globale kontorkatalog. Hva vil du vite?",
    assistantSubtitle: "Kunnskapsassistent for bedriften",
    welcomeEyebrow: "Velkommen", welcomeTitle: "Hei, jeg er AskVera.", welcomeBody: "Jeg kan hjelpe deg med å finne godkjente svar i Forever Livings selskapsretningslinjer og globale kontorkatalog.", welcomeNext: "Velg marked og språk for å begynne.",
    privacyTitle: "Personvern og vilkår", privacyBody: "Les og godta de nødvendige juridiske dokumentene for å bruke AskVera.", privacyAcknowledgment: "Jeg har lest og godtar de nødvendige personvern- og vilkårsdokumentene.", accept: "Jeg godtar", decline: "Ikke nå", inputPlaceholder: "Still et spørsmål", send: "Send",
    newChat: "Start ny chat", newChatConfirmation: "En ny chat avslutter og tømmer denne samtalen.", confirmNewChat: "Start chat", cancelNewChat: "Avbryt", support: "Be om hjelp", supportQueued: "Støtteforespørselen din er sendt. Referanse: {id}", supportFailed: "Støtteforespørselen kunne ikke opprettes. Prøv igjen.", supportCreating: "Oppretter...", supportRequested: "Forespurt", conversationCleared: "En ny chat er klar.",
    footer: "Svar genereres av KI fra godkjente firmadokumenter og kan inneholde feil. Kontroller viktig informasjon mot de oppgitte kildedokumentene.", online: "Online", offline: "Offline", reconnecting: "Kobler til igjen", consentRequired: "Godta personvernavtalen for å begynne.", unavailable: "AskVera er midlertidig utilgjengelig. Prøv igjen om litt.", waiting: "Vent til det gjeldende svaret er ferdig.", copy: "Kopier", copied: "Kopiert", helpful: "Nyttig", notHelpful: "Ikke nyttig",
    privacyEyebrow: "Et raskt personvernsteg", reviewDocuments: "Se gjennom nødvendige dokumenter", privacyLoading: "Laster juridiske dokumenter...", privacySaving: "Lagrer...", privacySaved: "Personvern lagret. Chatten er klar.", declineTitle: "Ikke noe problem. AskVera er her når du er klar.", declineBody: "Kom tilbake og godta personvern og vilkår for å begynne.", reviewPrivacy: "Se gjennom personvernvilkår", market: "Marked", language: "Språk", selectMarket: "Velg et marked", selectLanguage: "Velg et språk", openAssistant: "Åpne AskVera", closeAssistant: "Lukk AskVera", openMenu: "Åpne AskVera-meny", composerHint: "Enter for å sende. Shift + Enter for en ny linje.", thinking: "Tenker...", searching: "Søker i godkjent dokumentasjon...", generating: "Forbereder svaret ditt...", retrying: "Forbindelsen ble brutt. Prøver igjen...", slowResponse: "Jobber fortsatt...", you: "Du", system: "System", sourcesUsed: "Kilder brukt til dette svaret", references: "Referanser", primarySource: "Primærkilde", supportingSource: "Støttekilde", source: "Kilde", section: "Avsnitt", saveAsPdf: "Lagre som PDF", closeLegal: "Lukk juridisk dokument"
  },
  sr: {
    greeting: "Zdravo, ja sam AskVera. Mogu da vam pomognem da pronađete odobrene odgovore u pravilima kompanije Forever Living i globalnom imeniku kancelarija. Šta želite da saznate?",
    assistantSubtitle: "Poslovni asistent za informacije",
    welcomeEyebrow: "Dobro došli", welcomeTitle: "Zdravo, ja sam AskVera.", welcomeBody: "Mogu da vam pomognem da pronađete odobrene odgovore u pravilima kompanije Forever Living i globalnom imeniku kancelarija.", welcomeNext: "Izaberite tržište i jezik da biste počeli.",
    privacyTitle: "Privatnost i uslovi", privacyBody: "Pregledajte i prihvatite potrebna pravna dokumenta da biste koristili AskVera.", privacyAcknowledgment: "Pročitao/la sam i prihvatam potrebna dokumenta o privatnosti i uslovima.", accept: "Prihvatam", decline: "Ne sada", inputPlaceholder: "Postavite pitanje", send: "Pošalji",
    newChat: "Započni novi razgovor", newChatConfirmation: "Pokretanjem novog razgovora ovaj razgovor će biti završen i obrisan.", confirmNewChat: "Započni razgovor", cancelNewChat: "Otkaži", support: "Zatraži podršku", supportQueued: "Vaš zahtev za podršku je poslat. Referenca: {id}", supportFailed: "Zahtev za podršku nije moguće kreirati. Pokušajte ponovo.", supportCreating: "Kreiranje...", supportRequested: "Zatraženo", conversationCleared: "Novi razgovor je spreman.",
    supportFormTitle: "Zatraži podršku", supportFormBody: "Pošaljite pitanje timu za podršku za vaše tržište.", supportFirstName: "Ime", supportEmail: "E-adresa", supportQuestion: "Pitanje ili problem", supportSubmit: "Pošalji zahtev", supportCancel: "Otkaži", supportPrivacy: "Vaši podaci se koriste samo za odgovor na ovaj zahtev za podršku.", supportInvalidEmail: "Unesite važeću e-adresu.", supportNoRoute: "Zahtevi za podršku još nisu dostupni za ovo tržište.",
    footer: "Odgovore generiše AI na osnovu odobrenih dokumenata kompanije i mogu sadržati greške. Važne informacije proverite u navedenim izvornim dokumentima.", online: "Na mreži", offline: "Van mreže", reconnecting: "Ponovno povezivanje", consentRequired: "Prihvatite saglasnost za privatnost da biste počeli.", unavailable: "AskVera je privremeno nedostupna. Pokušajte ponovo za trenutak.", waiting: "Sačekajte da se trenutni odgovor završi.", copy: "Kopiraj", copied: "Kopirano", helpful: "Korisno", notHelpful: "Nije korisno",
    privacyEyebrow: "Jedan kratak korak za privatnost", reviewDocuments: "Pregledajte potrebna dokumenta", privacyLoading: "Učitavanje pravnih dokumenata...", privacySaving: "Čuvanje...", privacySaved: "Privatnost je sačuvana. Razgovor je spreman.", declineTitle: "Nema problema. AskVera će biti ovde kada budete spremni.", declineBody: "Da biste započeli razgovor, vratite se i prihvatite privatnost i uslove.", reviewPrivacy: "Pregledaj privatnost i uslove", market: "Tržište", language: "Jezik", selectMarket: "Izaberite tržište", selectLanguage: "Izaberite jezik", openAssistant: "Otvori AskVera", closeAssistant: "Zatvori AskVera", openMenu: "Otvori AskVera meni", composerHint: "Enter za slanje. Shift + Enter za novi red.", thinking: "Razmišljam...", searching: "Pretraživanje odobrene dokumentacije...", generating: "Priprema odgovora...", retrying: "Veza je prekinuta. Ponovni pokušaj...", slowResponse: "Još uvek radim...", you: "Vi", system: "Sistem", sourcesUsed: "Izvori korišćeni za ovaj odgovor", references: "Reference", primarySource: "Glavni izvor", supportingSource: "Dodatni izvor", source: "Izvor", section: "Odeljak", saveAsPdf: "Sačuvaj kao PDF", closeLegal: "Zatvori pravni dokument", retry: "Pokušaj ponovo"
  },
  sv: {
    greeting: "Hej, jag är AskVera. Jag kan hjälpa dig att hitta godkända svar i Forever Livings företagspolicyer och globala kontorskatalog. Vad vill du veta?",
    assistantSubtitle: "Företagets kunskapsassistent",
    welcomeEyebrow: "Välkommen", welcomeTitle: "Hej, jag är AskVera.", welcomeBody: "Jag kan hjälpa dig att hitta godkända svar i Forever Livings företagspolicyer och globala kontorskatalog.", welcomeNext: "Välj marknad och språk för att börja.",
    privacyTitle: "Integritet och villkor", privacyBody: "Granska och godkänn de juridiska dokument som krävs för att använda AskVera.", privacyAcknowledgment: "Jag har läst och godkänner de obligatoriska integritets- och villkorsdokumenten.", accept: "Jag godkänner", decline: "Inte nu", inputPlaceholder: "Ställ en fråga", send: "Skicka",
    newChat: "Starta ny chatt", newChatConfirmation: "En ny chatt avslutar och rensar den här konversationen.", confirmNewChat: "Starta chatt", cancelNewChat: "Avbryt", support: "Begär hjälp", supportQueued: "Din supportbegäran har skickats. Referens: {id}", supportFailed: "Supportbegäran kunde inte skapas. Försök igen.", supportCreating: "Skapar...", supportRequested: "Begärd", conversationCleared: "En ny chatt är klar.",
    supportFormTitle: "Begär support", supportFormBody: "Skicka din fråga till supportteamet för din marknad.", supportFirstName: "Förnamn", supportEmail: "E-post", supportQuestion: "Fråga eller ärende", supportSubmit: "Skicka begäran", supportCancel: "Avbryt", supportPrivacy: "Dina uppgifter används endast för att besvara denna supportbegäran.", supportInvalidEmail: "Ange en giltig e-postadress.", supportNoRoute: "Supportbegäran är ännu inte tillgänglig för denna marknad.",
    footer: "Svar genereras av AI från godkända företagsdokument och kan innehålla fel. Kontrollera viktig information mot de citerade källdokumenten.", online: "Online", offline: "Offline", reconnecting: "Ansluter igen", consentRequired: "Godkänn integritetsavtalet för att börja.", unavailable: "AskVera är tillfälligt otillgänglig. Försök igen om en stund.", waiting: "Vänta tills det aktuella svaret är klart.", copy: "Kopiera", copied: "Kopierat", helpful: "Hjälpsamt", notHelpful: "Inte hjälpsamt",
    privacyEyebrow: "Ett snabbt integritetssteg", reviewDocuments: "Granska obligatoriska dokument", privacyLoading: "Läser in juridiska dokument...", privacySaving: "Sparar...", privacySaved: "Integriteten har sparats. Chatten är klar.", declineTitle: "Inga problem. AskVera finns här när du är redo.", declineBody: "Kom tillbaka och godkänn integritet och villkor för att börja.", reviewPrivacy: "Granska integritetsvillkoren", market: "Marknad", language: "Språk", selectMarket: "Välj en marknad", selectLanguage: "Välj ett språk", openAssistant: "Öppna AskVera", closeAssistant: "Stäng AskVera", openMenu: "Öppna AskVera-menyn", composerHint: "Enter för att skicka. Shift + Enter för en ny rad.", thinking: "Tänker...", searching: "Söker i godkänd dokumentation...", generating: "Förbereder ditt svar...", retrying: "Anslutningen avbröts. Försöker igen...", slowResponse: "Arbetar fortfarande...", you: "Du", system: "System", sourcesUsed: "Källor som användes för detta svar", references: "Referenser", primarySource: "Primär källa", supportingSource: "Stödjande källa", source: "Källa", section: "Avsnitt", saveAsPdf: "Spara som PDF", closeLegal: "Stäng juridiskt dokument"
  }
};

type FeedbackCopy = Pick<
  WidgetCopy,
  | "feedbackLabel"
  | "feedbackPrivacyNote"
  | "feedbackPlaceholder"
  | "feedbackSend"
  | "feedbackSkip"
  | "feedbackSent"
  | "feedbackError"
>;

const feedbackCopy: Record<string, FeedbackCopy> = {
  en: {
    feedbackLabel: "Tell us how we could improve this answer (optional)",
    feedbackPrivacyNote: "Your feedback helps AskVera improve. Please do not include personal information.",
    feedbackPlaceholder: "For example: I was looking for the specific discount amount",
    feedbackSend: "Send feedback",
    feedbackSkip: "Skip",
    feedbackSent: "Feedback submitted. Thank you for helping us improve AskVera.",
    feedbackError: "We could not save your feedback. Please try again."
  },
  fr: {
    feedbackLabel: "Dites-nous comment améliorer cette réponse (facultatif)",
    feedbackPrivacyNote: "Vos commentaires aident AskVera à s'améliorer. N'incluez aucune information personnelle.",
    feedbackPlaceholder: "Par exemple : je cherchais le montant exact de la remise",
    feedbackSend: "Envoyer le commentaire",
    feedbackSkip: "Ignorer",
    feedbackSent: "Commentaire envoyé. Merci de nous aider à améliorer AskVera.",
    feedbackError: "Nous n'avons pas pu enregistrer votre commentaire. Veuillez réessayer."
  },
  es: {
    feedbackLabel: "Cuéntanos cómo podríamos mejorar esta respuesta (opcional)",
    feedbackPrivacyNote: "Tus comentarios ayudan a mejorar AskVera. No incluyas información personal.",
    feedbackPlaceholder: "Por ejemplo: buscaba el importe exacto del descuento",
    feedbackSend: "Enviar comentarios",
    feedbackSkip: "Omitir",
    feedbackSent: "Comentarios enviados. Gracias por ayudarnos a mejorar AskVera.",
    feedbackError: "No pudimos guardar tus comentarios. Inténtalo de nuevo."
  },
  de: {
    feedbackLabel: "Wie können wir diese Antwort verbessern? (optional)",
    feedbackPrivacyNote: "Ihr Feedback hilft AskVera, besser zu werden. Geben Sie keine persönlichen Daten an.",
    feedbackPlaceholder: "Zum Beispiel: Ich suchte nach dem genauen Rabattbetrag",
    feedbackSend: "Feedback senden",
    feedbackSkip: "Überspringen",
    feedbackSent: "Feedback gesendet. Vielen Dank, dass Sie uns helfen, AskVera zu verbessern.",
    feedbackError: "Ihr Feedback konnte nicht gespeichert werden. Bitte versuchen Sie es erneut."
  },
  nl: {
    feedbackLabel: "Vertel ons hoe we dit antwoord kunnen verbeteren (optioneel)",
    feedbackPrivacyNote: "Uw feedback helpt AskVera te verbeteren. Vermeld geen persoonlijke gegevens.",
    feedbackPlaceholder: "Bijvoorbeeld: ik zocht het exacte kortingsbedrag",
    feedbackSend: "Feedback verzenden",
    feedbackSkip: "Overslaan",
    feedbackSent: "Feedback verzonden. Bedankt dat u ons helpt AskVera te verbeteren.",
    feedbackError: "Uw feedback kon niet worden opgeslagen. Probeer het opnieuw."
  },
  it: {
    feedbackLabel: "Dicci come potremmo migliorare questa risposta (facoltativo)",
    feedbackPrivacyNote: "Il tuo feedback aiuta AskVera a migliorare. Non includere informazioni personali.",
    feedbackPlaceholder: "Ad esempio: cercavo l'importo esatto dello sconto",
    feedbackSend: "Invia feedback",
    feedbackSkip: "Salta",
    feedbackSent: "Feedback inviato. Grazie per aiutarci a migliorare AskVera.",
    feedbackError: "Non è stato possibile salvare il feedback. Riprova."
  },
  da: {
    feedbackLabel: "Fortæl os, hvordan vi kan forbedre dette svar (valgfrit)",
    feedbackPrivacyNote: "Din feedback hjælper AskVera med at blive bedre. Medtag ikke personlige oplysninger.",
    feedbackPlaceholder: "For eksempel: Jeg søgte efter det præcise rabatbeløb",
    feedbackSend: "Send feedback",
    feedbackSkip: "Spring over",
    feedbackSent: "Feedback sendt. Tak, fordi du hjælper os med at forbedre AskVera.",
    feedbackError: "Vi kunne ikke gemme din feedback. Prøv igen."
  },
  fi: {
    feedbackLabel: "Kerro, miten voisimme parantaa tätä vastausta (valinnainen)",
    feedbackPrivacyNote: "Palautteesi auttaa parantamaan AskVeraa. Älä lisää henkilötietoja.",
    feedbackPlaceholder: "Esimerkiksi: etsin tarkkaa alennuksen määrää",
    feedbackSend: "Lähetä palaute",
    feedbackSkip: "Ohita",
    feedbackSent: "Palaute lähetetty. Kiitos, että autat meitä parantamaan AskVeraa.",
    feedbackError: "Palautetta ei voitu tallentaa. Yritä uudelleen."
  },
  no: {
    feedbackLabel: "Fortell oss hvordan vi kan forbedre dette svaret (valgfritt)",
    feedbackPrivacyNote: "Tilbakemeldingen din hjelper AskVera med å bli bedre. Ikke ta med personopplysninger.",
    feedbackPlaceholder: "For eksempel: Jeg lette etter det nøyaktige rabattbeløpet",
    feedbackSend: "Send tilbakemelding",
    feedbackSkip: "Hopp over",
    feedbackSent: "Tilbakemelding sendt. Takk for at du hjelper oss med å forbedre AskVera.",
    feedbackError: "Vi kunne ikke lagre tilbakemeldingen. Prøv igjen."
  },
  sr: {
    feedbackLabel: "Recite nam kako možemo da poboljšamo ovaj odgovor (opciono)",
    feedbackPrivacyNote: "Vaše povratne informacije pomažu da AskVera bude bolja. Ne unosite lične podatke.",
    feedbackPlaceholder: "Na primer: tražio/la sam tačan iznos popusta",
    feedbackSend: "Pošalji povratne informacije",
    feedbackSkip: "Preskoči",
    feedbackSent: "Povratne informacije su poslate. Hvala što nam pomažete da poboljšamo AskVera.",
    feedbackError: "Nismo mogli da sačuvamo povratne informacije. Pokušajte ponovo."
  },
  sv: {
    feedbackLabel: "Berätta hur vi kan förbättra det här svaret (valfritt)",
    feedbackPrivacyNote: "Din feedback hjälper AskVera att bli bättre. Ta inte med personuppgifter.",
    feedbackPlaceholder: "Till exempel: Jag letade efter det exakta rabattbeloppet",
    feedbackSend: "Skicka feedback",
    feedbackSkip: "Hoppa över",
    feedbackSent: "Feedback skickad. Tack för att du hjälper oss att förbättra AskVera.",
    feedbackError: "Vi kunde inte spara din feedback. Försök igen."
  },
  ru: {
    feedbackLabel: "Расскажите, как можно улучшить этот ответ (необязательно)",
    feedbackPrivacyNote: "Ваш отзыв помогает улучшать AskVera. Не указывайте персональные данные.",
    feedbackPlaceholder: "Например: мне нужна была точная сумма скидки",
    feedbackSend: "Отправить отзыв",
    feedbackSkip: "Пропустить",
    feedbackSent: "Отзыв отправлен. Спасибо, что помогаете улучшать AskVera.",
    feedbackError: "Не удалось сохранить отзыв. Повторите попытку."
  }
};

export function getWidgetCopy(language?: string): WidgetCopy {
  const english = copy.en as WidgetCopy;
  const languageCode = (language || "en").split("-", 1)[0].toLowerCase();
  const retry = {
    da: "Prøv igen", de: "Erneut versuchen", es: "Reintentar", fi: "Yritä uudelleen",
    fr: "Réessayer", it: "Riprova", nl: "Opnieuw proberen", no: "Prøv igjen", ru: "Повторить", sv: "Försök igen"
  }[languageCode];
  return {
    ...english,
    ...feedbackCopy.en,
    ...(copy[languageCode] || {}),
    ...(feedbackCopy[languageCode] || {}),
    ...(retry ? { retry } : {})
  };
}
