"""Denied topic definitions used before and after generation."""

DENIED_TOPICS = {
    "income_claim": [
        "guaranteed income",
        "guaranteed earnings",
        "earnings guarantee",
        "earn a lot of money",
        "how much will i earn",
        "how much can i earn",
        "make money fast",
        "earn per month",
        "financial freedom",
        "replace my salary",
        "passive income",
        "get rich",
    ],
    "medical_claim": [
        "cure",
        "treatment",
        "treat disease",
        "diagnose",
        "fda approved",
        "medical advice",
        "help my arthritis",
        "help with arthritis",
        "help my diabetes",
        "help with diabetes",
        "lower my blood pressure",
        "heal cancer",
        "sunburn",
        "for a headache",
        "for headaches",
        "help a headache",
        "help with a headache",
        "headache relief",
        "cure a headache",
        "treat a headache",
        "acne",
    ],
    "off_topic": [
        "politics",
        "gambling",
        "weapons",
    ],
}
